### ISSUE TITLE
could not use another port for testing in local (only port 80 that works in port forwarding)

### ISSUE THREAD

**Issue by mir161803** [fly-apps/wordpress-sqlite#5]
using port 80, the project work just fine, but when i try to tweek it a little bit to use other port, it could not works.

here's my compose.yaml
```
services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
```
